version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          name: 'API Tests'
          debug: 'cypress:cli'
          requires:
            - cypress/install
          #start: 'lerna run start --parallel'
          install-command: 'npm install --no-optional --unsafe-perm'
          post-steps:
            - store_artifacts:
                path: 'mochawesome-report'
